<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2017r3sp1

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" exclude-result-prefixes="xs">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/">
		<xsl:variable name="var1_initial" select="."/>
		<FACTURA xmlns:stl="http://www.codesynthesis.com/projects/xsstl/xsstl" xmlns:ns2="urn:oasis:names:specification:ubl:codelist:gc:AllowanceChargeReasonCode-2.0" xmlns:ns3="urn:oasis:names:specification:ubl:codelist:gc:PaymentMeansCode-2.0" xmlns:ns1="urn:un:unece:uncefact:codelist:specification:54217:2001" xmlns:clm66411="urn:un:unece:uncefact:codelist:specification:66411:2001">
			<xsl:attribute name="xsi:noNamespaceSchemaLocation">file:///C:/Mapeo-carvajal/xsd/Factura%20Electr%C3%B3nica%20Colombia%20Alianza%20V3-0.xsd</xsl:attribute>
			<ENC>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var2_cur" select="."/>
					<ENC_1>
						<xsl:if test="not((translate(identificador_de_documento/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="identificador_de_documento"/>
						</xsl:if>
					</ENC_1>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var3_cur" select="."/>
					<ENC_2>
						<xsl:if test="not((translate(nit_un_emisor/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="number(nit_un_emisor)"/>
						</xsl:if>
					</ENC_2>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var4_cur" select="."/>
					<ENC_3>
						<xsl:if test="not((translate(nit_adquiriente/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="number(nit_adquiriente)"/>
						</xsl:if>
					</ENC_3>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var5_cur" select="."/>
					<ENC_4>
						<xsl:if test="not((translate(ubl_versionid/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="ubl_versionid"/>
						</xsl:if>
					</ENC_4>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var6_cur" select="."/>
					<ENC_5>
						<xsl:if test="not((translate(ubl_versionformato/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="ubl_versionformato"/>
						</xsl:if>
					</ENC_5>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var7_cur" select="."/>
					<ENC_6>
						<xsl:if test="not((translate(numero_oficial_de/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="numero_oficial_de"/>
						</xsl:if>
					</ENC_6>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var8_cur" select="."/>
					<ENC_7>
						<xsl:if test="not((translate(fecha_oficial_de/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="fecha_oficial_de"/>
						</xsl:if>
					</ENC_7>
				</xsl:for-each>
				<ENC_8>
					<xsl:value-of select="'00:00:00'"/>
				</ENC_8>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var9_cur" select="."/>
					<ENC_9>
						<xsl:if test="not((translate(tipo_documento_emisor/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="tipo_documento_emisor"/>
						</xsl:if>
					</ENC_9>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var10_cur" select="."/>
					<ENC_10>
						<xsl:if test="not((translate(codigo_moneda_emisor/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="codigo_moneda_emisor"/>
						</xsl:if>
					</ENC_10>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var11_cur" select="."/>
					<ENC_16>
						<xsl:if test="not((translate(fecha_vencimiento/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="fecha_vencimiento"/>
						</xsl:if>
					</ENC_16>
				</xsl:for-each>
			</ENC>
			<EMI>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var12_cur" select="."/>
					<EMI_1>
						<xsl:if test="not((translate(tipo_persona_emisor/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="number(tipo_persona_emisor)"/>
						</xsl:if>
					</EMI_1>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var13_cur" select="."/>
					<EMI_2>
						<xsl:if test="not((translate(nit_un_emisor/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="number(nit_un_emisor)"/>
						</xsl:if>
					</EMI_2>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var14_cur" select="."/>
					<EMI_3>
						<xsl:if test="not((translate(tipo_adquiriente_emisor/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="tipo_adquiriente_emisor"/>
						</xsl:if>
					</EMI_3>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var15_cur" select="."/>
					<EMI_4>
						<xsl:if test="not((translate(tipo_regimen_emisor/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="number(tipo_regimen_emisor)"/>
						</xsl:if>
					</EMI_4>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var16_cur" select="."/>
					<EMI_6>
						<xsl:if test="not((translate(nombre_legal_un_emisor/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="nombre_legal_un_emisor"/>
						</xsl:if>
					</EMI_6>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var17_cur" select="."/>
					<EMI_7>
						<xsl:if test="not((translate(nombre_comercial_un_emisor/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="nombre_comercial_un_emisor"/>
						</xsl:if>
					</EMI_7>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var18_cur" select="."/>
					<EMI_10>
						<xsl:if test="not((translate(direccion_emisor/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="direccion_emisor"/>
						</xsl:if>
					</EMI_10>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var19_cur" select="."/>
					<EMI_11>
						<xsl:if test="not((translate(departamento_emisor/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="departamento_emisor"/>
						</xsl:if>
					</EMI_11>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var20_cur" select="."/>
					<EMI_12>
						<xsl:if test="not((translate(barrio_emisor/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="barrio_emisor"/>
						</xsl:if>
					</EMI_12>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var21_cur" select="."/>
					<EMI_13>
						<xsl:if test="not((translate(ciudad_emisor/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="ciudad_emisor"/>
						</xsl:if>
					</EMI_13>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var22_cur" select="."/>
					<EMI_14>
						<xsl:if test="not((translate(codigo_postal_emisor/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="codigo_postal_emisor"/>
						</xsl:if>
					</EMI_14>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var23_cur" select="."/>
					<EMI_15>
						<xsl:if test="not((translate(codigo_pais_emisor/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="codigo_pais_emisor"/>
						</xsl:if>
					</EMI_15>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var24_cur" select="."/>
					<EMI_16>
						<xsl:if test="not((translate(ean_emisor/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="ean_emisor"/>
						</xsl:if>
					</EMI_16>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var25_cur" select="."/>
					<EMI_17>
						<xsl:if test="not((translate(Numero_matricula_mercantil/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="Numero_matricula_mercantil"/>
						</xsl:if>
					</EMI_17>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var26_cur" select="."/>
					<EMI_18>
						<xsl:if test="not((translate(direccion_emisor/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="direccion_emisor"/>
						</xsl:if>
					</EMI_18>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var27_cur" select="."/>
					<EMI_19>
						<xsl:if test="not((translate(departamento_emisor/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="departamento_emisor"/>
						</xsl:if>
					</EMI_19>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var28_cur" select="."/>
					<EMI_20>
						<xsl:if test="not((translate(nombre_centro_operacion_emisor/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="nombre_centro_operacion_emisor"/>
						</xsl:if>
					</EMI_20>
				</xsl:for-each>
				<xsl:for-each select="dsxml">
					<xsl:variable name="var29_cur" select="."/>
					<xsl:for-each select="informacion_tributaria_emi_xml">
						<xsl:variable name="var30_cur" select="."/>
						<TAC>
							<TAC_1>
								<xsl:if test="not((translate(codigo/@xsi:nil, 'true ', '1') = '1'))">
									<xsl:value-of select="codigo"/>
								</xsl:if>
							</TAC_1>
							<xsl:for-each select="$var29_cur/encabezado_xml">
								<xsl:variable name="var31_cur" select="."/>
								<TAC_2>
									<xsl:if test="not((translate(nombre_comercial_un_emisor/@xsi:nil, 'true ', '1') = '1'))">
										<xsl:value-of select="nombre_comercial_un_emisor"/>
									</xsl:if>
								</TAC_2>
							</xsl:for-each>
							<xsl:for-each select="$var29_cur/encabezado_xml">
								<xsl:variable name="var32_cur" select="."/>
								<TAC_3>
									<xsl:if test="not((translate(nit_un_emisor/@xsi:nil, 'true ', '1') = '1'))">
										<xsl:value-of select="number(nit_un_emisor)"/>
									</xsl:if>
								</TAC_3>
							</xsl:for-each>
							<xsl:for-each select="$var29_cur/encabezado_xml">
								<xsl:variable name="var33_cur" select="."/>
								<TAC_4>
									<xsl:if test="not((translate(tipo_adquiriente_emisor/@xsi:nil, 'true ', '1') = '1'))">
										<xsl:value-of select="tipo_adquiriente_emisor"/>
									</xsl:if>
								</TAC_4>
							</xsl:for-each>
							<xsl:for-each select="$var29_cur/encabezado_xml">
								<xsl:variable name="var34_cur" select="."/>
								<TAC_5>
									<xsl:if test="not((translate(barrio_centro_operacion_rut/@xsi:nil, 'true ', '1') = '1'))">
										<xsl:value-of select="barrio_centro_operacion_rut"/>
									</xsl:if>
								</TAC_5>
							</xsl:for-each>
							<xsl:for-each select="$var29_cur/encabezado_xml">
								<xsl:variable name="var35_cur" select="."/>
								<TAC_6>
									<xsl:if test="not((translate(ciudad_centro_operacion_rut/@xsi:nil, 'true ', '1') = '1'))">
										<xsl:value-of select="ciudad_centro_operacion_rut"/>
									</xsl:if>
								</TAC_6>
							</xsl:for-each>
							<xsl:for-each select="$var29_cur/encabezado_xml">
								<xsl:variable name="var36_cur" select="."/>
								<TAC_7>
									<xsl:if test="not((translate(codigo_postal_emisor/@xsi:nil, 'true ', '1') = '1'))">
										<xsl:value-of select="codigo_postal_emisor"/>
									</xsl:if>
								</TAC_7>
							</xsl:for-each>
							<xsl:for-each select="$var29_cur/encabezado_xml">
								<xsl:variable name="var37_cur" select="."/>
								<TAC_8>
									<xsl:if test="not((translate(Dpto_Centro_operacion_rut/@xsi:nil, 'true ', '1') = '1'))">
										<xsl:value-of select="Dpto_Centro_operacion_rut"/>
									</xsl:if>
								</TAC_8>
							</xsl:for-each>
							<xsl:for-each select="$var29_cur/encabezado_xml">
								<xsl:variable name="var38_cur" select="."/>
								<TAC_9>
									<xsl:if test="not((translate(direccion_centro_operacion_rut/@xsi:nil, 'true ', '1') = '1'))">
										<xsl:value-of select="direccion_centro_operacion_rut"/>
									</xsl:if>
								</TAC_9>
							</xsl:for-each>
							<xsl:for-each select="$var29_cur/encabezado_xml">
								<xsl:variable name="var39_cur" select="."/>
								<TAC_10>
									<xsl:if test="not((translate(codigo_pais_emisor/@xsi:nil, 'true ', '1') = '1'))">
										<xsl:value-of select="codigo_pais_emisor"/>
									</xsl:if>
								</TAC_10>
							</xsl:for-each>
						</TAC>
					</xsl:for-each>
				</xsl:for-each>
				<ICC>
					<xsl:for-each select="dsxml/encabezado_xml">
						<xsl:variable name="var40_cur" select="."/>
						<ICC_1>
							<xsl:if test="not((translate(Numero_matricula_mercantil/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="Numero_matricula_mercantil"/>
							</xsl:if>
						</ICC_1>
					</xsl:for-each>
					<xsl:for-each select="dsxml/encabezado_xml">
						<xsl:variable name="var41_cur" select="."/>
						<ICC_2>
							<xsl:if test="not((translate(Barrio_Centro_operacion_icc/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="Barrio_Centro_operacion_icc"/>
							</xsl:if>
						</ICC_2>
					</xsl:for-each>
					<xsl:for-each select="dsxml/encabezado_xml">
						<xsl:variable name="var42_cur" select="."/>
						<ICC_3>
							<xsl:if test="not((translate(Ciudad_Centro_Operacion_icc/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="Ciudad_Centro_Operacion_icc"/>
							</xsl:if>
						</ICC_3>
					</xsl:for-each>
					<xsl:for-each select="dsxml/encabezado_xml">
						<xsl:variable name="var43_cur" select="."/>
						<ICC_4>
							<xsl:if test="not((translate(codigo_postal_emisor/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="codigo_postal_emisor"/>
							</xsl:if>
						</ICC_4>
					</xsl:for-each>
					<xsl:for-each select="dsxml/encabezado_xml">
						<xsl:variable name="var44_cur" select="."/>
						<ICC_5>
							<xsl:if test="not((translate(Dpto_Centro_operacion_icc/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="Dpto_Centro_operacion_icc"/>
							</xsl:if>
						</ICC_5>
					</xsl:for-each>
					<xsl:for-each select="dsxml/encabezado_xml">
						<xsl:variable name="var45_cur" select="."/>
						<ICC_6>
							<xsl:if test="not((translate(Direccion_centro_operacion_adq/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="Direccion_centro_operacion_adq"/>
							</xsl:if>
						</ICC_6>
					</xsl:for-each>
					<xsl:for-each select="dsxml/encabezado_xml">
						<xsl:variable name="var46_cur" select="."/>
						<ICC_7>
							<xsl:if test="not((translate(codigo_pais_emisor/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="codigo_pais_emisor"/>
							</xsl:if>
						</ICC_7>
					</xsl:for-each>
				</ICC>
				<CDE>
					<CDE_1>
						<xsl:value-of select="number('1')"/>
					</CDE_1>
					<xsl:for-each select="dsxml/encabezado_xml">
						<xsl:variable name="var47_cur" select="."/>
						<CDE_2>
							<xsl:if test="not((translate(contacto_comercial_emisor/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="contacto_comercial_emisor"/>
							</xsl:if>
						</CDE_2>
					</xsl:for-each>
					<xsl:for-each select="dsxml/encabezado_xml">
						<xsl:variable name="var48_cur" select="."/>
						<CDE_3>
							<xsl:if test="not((translate(contacto_telefonos_emisor/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="contacto_telefonos_emisor"/>
							</xsl:if>
						</CDE_3>
					</xsl:for-each>
					<xsl:for-each select="dsxml/encabezado_xml">
						<xsl:variable name="var49_cur" select="."/>
						<CDE_4>
							<xsl:if test="not((translate(contacto_email_emisor/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="contacto_email_emisor"/>
							</xsl:if>
						</CDE_4>
					</xsl:for-each>
				</CDE>
			</EMI>
			<ADQ>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var50_cur" select="."/>
					<ADQ_1>
						<xsl:if test="not((translate(tipo_persona_adquiriente/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="number(tipo_persona_adquiriente)"/>
						</xsl:if>
					</ADQ_1>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var51_cur" select="."/>
					<ADQ_2>
						<xsl:if test="not((translate(nit_adquiriente/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="number(nit_adquiriente)"/>
						</xsl:if>
					</ADQ_2>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var52_cur" select="."/>
					<ADQ_3>
						<xsl:if test="not((translate(codigo_identificacion_adquirie/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="codigo_identificacion_adquirie"/>
						</xsl:if>
					</ADQ_3>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var53_cur" select="."/>
					<ADQ_4>
						<xsl:if test="not((translate(tipo_regimen_adquiriente/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="number(tipo_regimen_adquiriente)"/>
						</xsl:if>
					</ADQ_4>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var54_cur" select="."/>
					<ADQ_5>
						<xsl:if test="not((translate(importer_number/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="importer_number"/>
						</xsl:if>
					</ADQ_5>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var55_cur" select="."/>
					<ADQ_6>
						<xsl:if test="not((translate(razon_social_adquiriente/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="razon_social_adquiriente"/>
						</xsl:if>
					</ADQ_6>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var56_cur" select="."/>
					<ADQ_7>
						<xsl:if test="not((translate(nombre_adquiriente/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="nombre_adquiriente"/>
						</xsl:if>
					</ADQ_7>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var57_cur" select="."/>
					<ADQ_8>
						<xsl:if test="not((translate(primer_nombre_adquiriente/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="primer_nombre_adquiriente"/>
						</xsl:if>
					</ADQ_8>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var58_cur" select="."/>
					<ADQ_9>
						<xsl:if test="not((translate(apellido_adquiriente/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="apellido_adquiriente"/>
						</xsl:if>
					</ADQ_9>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var59_cur" select="."/>
					<ADQ_10>
						<xsl:if test="not((translate(direccion_adquiriente/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="direccion_adquiriente"/>
						</xsl:if>
					</ADQ_10>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var60_cur" select="."/>
					<ADQ_11>
						<xsl:if test="not((translate(dpto_adquiriente/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="dpto_adquiriente"/>
						</xsl:if>
					</ADQ_11>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var61_cur" select="."/>
					<ADQ_12>
						<xsl:if test="not((translate(barrio_adquiriente/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="barrio_adquiriente"/>
						</xsl:if>
					</ADQ_12>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var62_cur" select="."/>
					<ADQ_13>
						<xsl:if test="not((translate(ciudad_adquiriente/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="ciudad_adquiriente"/>
						</xsl:if>
					</ADQ_13>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var63_cur" select="."/>
					<ADQ_14>
						<xsl:if test="not((translate(Codigo_postal_adq/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="Codigo_postal_adq"/>
						</xsl:if>
					</ADQ_14>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var64_cur" select="."/>
					<ADQ_15>
						<xsl:if test="not((translate(pais_adquiriente/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="pais_adquiriente"/>
						</xsl:if>
					</ADQ_15>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var65_cur" select="."/>
					<ADQ_16>
						<xsl:if test="not((translate(ean_adquiriente/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="ean_adquiriente"/>
						</xsl:if>
					</ADQ_16>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var66_cur" select="."/>
					<ADQ_17>
						<xsl:if test="not((translate(Numero_matricula_mercantil_adq/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="Numero_matricula_mercantil_adq"/>
						</xsl:if>
					</ADQ_17>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var67_cur" select="."/>
					<ADQ_18>
						<xsl:if test="not((translate(direccion_postal_adquiriente/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="direccion_postal_adquiriente"/>
						</xsl:if>
					</ADQ_18>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var68_cur" select="."/>
					<ADQ_19>
						<xsl:if test="not((translate(dpto_adquiriente/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="dpto_adquiriente"/>
						</xsl:if>
					</ADQ_19>
				</xsl:for-each>
				<xsl:for-each select="dsxml">
					<xsl:variable name="var69_cur" select="."/>
					<xsl:for-each select="informacion_tributaria_adq_xml">
						<xsl:variable name="var70_cur" select="."/>
						<TCR>
							<TCR_1>
								<xsl:if test="not((translate(codigo/@xsi:nil, 'true ', '1') = '1'))">
									<xsl:value-of select="codigo"/>
								</xsl:if>
							</TCR_1>
							<xsl:for-each select="$var69_cur/encabezado_xml">
								<xsl:variable name="var71_cur" select="."/>
								<TCR_3>
									<xsl:if test="not((translate(nit_adquiriente/@xsi:nil, 'true ', '1') = '1'))">
										<xsl:value-of select="number(nit_adquiriente)"/>
									</xsl:if>
								</TCR_3>
							</xsl:for-each>
							<xsl:for-each select="$var69_cur/encabezado_xml">
								<xsl:variable name="var72_cur" select="."/>
								<TCR_4>
									<xsl:if test="not((translate(codigo_identificacion_adquirie/@xsi:nil, 'true ', '1') = '1'))">
										<xsl:value-of select="codigo_identificacion_adquirie"/>
									</xsl:if>
								</TCR_4>
							</xsl:for-each>
							<xsl:for-each select="$var69_cur/encabezado_xml">
								<xsl:variable name="var73_cur" select="."/>
								<TCR_5>
									<xsl:if test="not((translate(Barrio_Centro_operacion_rut_adq/@xsi:nil, 'true ', '1') = '1'))">
										<xsl:value-of select="Barrio_Centro_operacion_rut_adq"/>
									</xsl:if>
								</TCR_5>
							</xsl:for-each>
							<xsl:for-each select="$var69_cur/encabezado_xml">
								<xsl:variable name="var74_cur" select="."/>
								<TCR_6>
									<xsl:if test="not((translate(Ciudad_Centro_Operacion_rut_adq/@xsi:nil, 'true ', '1') = '1'))">
										<xsl:value-of select="Ciudad_Centro_Operacion_rut_adq"/>
									</xsl:if>
								</TCR_6>
							</xsl:for-each>
							<xsl:for-each select="$var69_cur/encabezado_xml">
								<xsl:variable name="var75_cur" select="."/>
								<TCR_7>
									<xsl:if test="not((translate(Codigo_postal_adq/@xsi:nil, 'true ', '1') = '1'))">
										<xsl:value-of select="Codigo_postal_adq"/>
									</xsl:if>
								</TCR_7>
							</xsl:for-each>
							<xsl:for-each select="$var69_cur/encabezado_xml">
								<xsl:variable name="var76_cur" select="."/>
								<TCR_8>
									<xsl:if test="not((translate(Dpto_Centro_operacion_rut_adq/@xsi:nil, 'true ', '1') = '1'))">
										<xsl:value-of select="Dpto_Centro_operacion_rut_adq"/>
									</xsl:if>
								</TCR_8>
							</xsl:for-each>
							<xsl:for-each select="$var69_cur/encabezado_xml">
								<xsl:variable name="var77_cur" select="."/>
								<TCR_9>
									<xsl:if test="not((translate(Direccion_centro_operacion_adq/@xsi:nil, 'true ', '1') = '1'))">
										<xsl:value-of select="Direccion_centro_operacion_adq"/>
									</xsl:if>
								</TCR_9>
							</xsl:for-each>
							<xsl:for-each select="$var69_cur/encabezado_xml">
								<xsl:variable name="var78_cur" select="."/>
								<TCR_10>
									<xsl:if test="not((translate(pais_adquiriente/@xsi:nil, 'true ', '1') = '1'))">
										<xsl:value-of select="pais_adquiriente"/>
									</xsl:if>
								</TCR_10>
							</xsl:for-each>
						</TCR>
					</xsl:for-each>
				</xsl:for-each>
				<xsl:for-each select="dsxml/informacion_camara_adquiriente">
					<xsl:variable name="var79_cur" select="."/>
					<ICR>
						<ICR_1>
							<xsl:if test="not((translate(Numero_matricula_mercantil_adq/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="Numero_matricula_mercantil_adq"/>
							</xsl:if>
						</ICR_1>
						<ICR_2>
							<xsl:if test="not((translate(Barrio_Centro_operacion_icc_adq/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="Barrio_Centro_operacion_icc_adq"/>
							</xsl:if>
						</ICR_2>
						<ICR_3>
							<xsl:if test="not((translate(Ciudad_Centro_Operacion_icc_adq/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="Ciudad_Centro_Operacion_icc_adq"/>
							</xsl:if>
						</ICR_3>
						<ICR_4>
							<xsl:if test="not((translate(Codigo_postal_adq/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="Codigo_postal_adq"/>
							</xsl:if>
						</ICR_4>
						<ICR_5>
							<xsl:if test="not((translate(Dpto_Centro_operacion_icc_adq/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="Dpto_Centro_operacion_icc_adq"/>
							</xsl:if>
						</ICR_5>
						<ICR_6>
							<xsl:if test="not((translate(Direccion_centro_operacion_icc_a/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="Direccion_centro_operacion_icc_a"/>
							</xsl:if>
						</ICR_6>
						<ICR_7>
							<xsl:if test="not((translate(Codigo_pais_emisor_icc_adq/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="Codigo_pais_emisor_icc_adq"/>
							</xsl:if>
						</ICR_7>
						<ICR_8>
							<xsl:if test="not((translate(Nombre_pais_emisor_icc_adq/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="Nombre_pais_emisor_icc_adq"/>
							</xsl:if>
						</ICR_8>
					</ICR>
				</xsl:for-each>
				<CDA>
					<CDA_1>
						<xsl:value-of select="number('1')"/>
					</CDA_1>
					<xsl:for-each select="dsxml/encabezado_xml">
						<xsl:variable name="var80_cur" select="."/>
						<CDA_2>
							<xsl:if test="not((translate(contacto_comprador_adquiriente/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="contacto_comprador_adquiriente"/>
							</xsl:if>
						</CDA_2>
					</xsl:for-each>
					<xsl:for-each select="dsxml/encabezado_xml">
						<xsl:variable name="var81_cur" select="."/>
						<CDA_3>
							<xsl:if test="not((translate(contacto_telefonos_adquiriente/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="contacto_telefonos_adquiriente"/>
							</xsl:if>
						</CDA_3>
					</xsl:for-each>
					<xsl:for-each select="dsxml/encabezado_xml">
						<xsl:variable name="var82_cur" select="."/>
						<CDA_4>
							<xsl:if test="not((translate(contacto_email_adquiriente/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="contacto_email_adquiriente"/>
							</xsl:if>
						</CDA_4>
					</xsl:for-each>
				</CDA>
			</ADQ>
			<TOT>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var83_cur" select="."/>
					<TOT_1>
						<xsl:if test="not((translate(total_importe_bruto/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="number(total_importe_bruto)"/>
						</xsl:if>
					</TOT_1>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var84_cur" select="."/>
					<TOT_2>
						<xsl:if test="not((translate(codigo_moneda_emisor/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="codigo_moneda_emisor"/>
						</xsl:if>
					</TOT_2>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var85_cur" select="."/>
					<TOT_3>
						<xsl:if test="not((translate(total_base_imponible/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="number(total_base_imponible)"/>
						</xsl:if>
					</TOT_3>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var86_cur" select="."/>
					<TOT_4>
						<xsl:if test="not((translate(codigo_moneda_emisor/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="codigo_moneda_emisor"/>
						</xsl:if>
					</TOT_4>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var87_cur" select="."/>
					<TOT_5>
						<xsl:if test="not((translate(valor_total_doc_rg/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="valor_total_doc_rg"/>
						</xsl:if>
					</TOT_5>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var88_cur" select="."/>
					<TOT_6>
						<xsl:if test="not((translate(codigo_moneda_emisor/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="codigo_moneda_emisor"/>
						</xsl:if>
					</TOT_6>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var89_cur" select="."/>
					<TOT_7>
						<xsl:if test="not((translate(total_importe_retenido/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="number(total_importe_retenido)"/>
						</xsl:if>
					</TOT_7>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var90_cur" select="."/>
					<TOT_8>
						<xsl:if test="not((translate(codigo_moneda_emisor/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="codigo_moneda_emisor"/>
						</xsl:if>
					</TOT_8>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var91_cur" select="."/>
					<TOT_9>
						<xsl:if test="not((translate(valor_total_descuento/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="number(valor_total_descuento)"/>
						</xsl:if>
					</TOT_9>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var92_cur" select="."/>
					<TOT_10>
						<xsl:if test="not((translate(codigo_moneda_emisor/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="codigo_moneda_emisor"/>
						</xsl:if>
					</TOT_10>
				</xsl:for-each>
			</TOT>
			<xsl:for-each select="dsxml">
				<xsl:variable name="var93_cur" select="."/>
				<xsl:for-each select="resumen_impto_xml">
					<xsl:variable name="var94_cur" select="."/>
					<TIM>
						<TIM_1>
							<xsl:if test="not((translate(retenido/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="boolean(translate(normalize-space(string(retenido)), ' 0false', ''))"/>
							</xsl:if>
						</TIM_1>
						<TIM_2>
							<xsl:if test="not((translate(importe_impuesto/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="number(importe_impuesto)"/>
							</xsl:if>
						</TIM_2>
						<xsl:for-each select="$var93_cur/encabezado_xml">
							<xsl:variable name="var95_cur" select="."/>
							<TIM_3>
								<xsl:if test="not((translate(codigo_moneda_emisor/@xsi:nil, 'true ', '1') = '1'))">
									<xsl:value-of select="codigo_moneda_emisor"/>
								</xsl:if>
							</TIM_3>
						</xsl:for-each>
						<xsl:for-each select="detalle_resumen_impto_xml">
							<xsl:variable name="var96_cur" select="."/>
							<IMP>
								<IMP_1>
									<xsl:if test="not((translate(codigo_impuesto_dian/@xsi:nil, 'true ', '1') = '1'))">
										<xsl:value-of select="codigo_impuesto_dian"/>
									</xsl:if>
								</IMP_1>
								<IMP_2>
									<xsl:if test="not((translate(base_imponible/@xsi:nil, 'true ', '1') = '1'))">
										<xsl:value-of select="number(base_imponible)"/>
									</xsl:if>
								</IMP_2>
								<xsl:for-each select="$var93_cur/encabezado_xml">
									<xsl:variable name="var97_cur" select="."/>
									<IMP_3>
										<xsl:if test="not((translate(codigo_moneda_emisor/@xsi:nil, 'true ', '1') = '1'))">
											<xsl:value-of select="codigo_moneda_emisor"/>
										</xsl:if>
									</IMP_3>
								</xsl:for-each>
								<IMP_4>
									<xsl:if test="not((translate(importe_impuesto/@xsi:nil, 'true ', '1') = '1'))">
										<xsl:value-of select="number(importe_impuesto)"/>
									</xsl:if>
								</IMP_4>
								<xsl:for-each select="$var93_cur/encabezado_xml">
									<xsl:variable name="var98_cur" select="."/>
									<IMP_5>
										<xsl:if test="not((translate(codigo_moneda_emisor/@xsi:nil, 'true ', '1') = '1'))">
											<xsl:value-of select="codigo_moneda_emisor"/>
										</xsl:if>
									</IMP_5>
								</xsl:for-each>
								<IMP_6>
									<xsl:if test="not((translate(porcentaje/@xsi:nil, 'true ', '1') = '1'))">
										<xsl:value-of select="number(porcentaje)"/>
									</xsl:if>
								</IMP_6>
							</IMP>
						</xsl:for-each>
					</TIM>
				</xsl:for-each>
			</xsl:for-each>
			<xsl:for-each select="dsxml/terminos_de_negociacion_xml">
				<xsl:variable name="var99_cur" select="."/>
				<TDC>
					<TDC_1>
						<xsl:if test="not((translate(moneda_origen/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="moneda_origen"/>
						</xsl:if>
					</TDC_1>
					<TDC_2>
						<xsl:if test="not((translate(moneda_destino/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="moneda_destino"/>
						</xsl:if>
					</TDC_2>
					<TDC_3>
						<xsl:if test="not((translate(valor_trm_negociada/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="number(valor_trm_negociada)"/>
						</xsl:if>
					</TDC_3>
					<TDC_4>
						<xsl:if test="not((translate(fecha_trm/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="fecha_trm"/>
						</xsl:if>
					</TDC_4>
				</TDC>
			</xsl:for-each>
			<xsl:for-each select="dsxml">
				<xsl:variable name="var100_cur" select="."/>
				<xsl:for-each select="desgloce_neg_xml">
					<xsl:variable name="var101_cur" select="."/>
					<DSC>
						<DSC_1>
							<xsl:value-of select="boolean(translate(normalize-space('True'), ' 0false', ''))"/>
						</DSC_1>
						<DSC_2>
							<xsl:value-of select="number('0')"/>
						</DSC_2>
						<DSC_3>
							<xsl:if test="not((translate(valor_desglose_rg/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="valor_desglose_rg"/>
							</xsl:if>
						</DSC_3>
						<xsl:for-each select="$var100_cur/terminos_de_negociacion_xml">
							<xsl:variable name="var102_cur" select="."/>
							<DSC_4>
								<xsl:if test="not((translate(moneda_destino/@xsi:nil, 'true ', '1') = '1'))">
									<xsl:value-of select="moneda_destino"/>
								</xsl:if>
							</DSC_4>
						</xsl:for-each>
						<DSC_5>
							<xsl:value-of select="'8'"/>
						</DSC_5>
						<DSC_6>
							<xsl:if test="not((translate(cargos_homo/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="cargos_homo"/>
							</xsl:if>
						</DSC_6>
					</DSC>
				</xsl:for-each>
			</xsl:for-each>
			<DRF>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var103_cur" select="."/>
					<DRF_1>
						<xsl:if test="not((translate(s_num_autorizacion_resol_dian/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="s_num_autorizacion_resol_dian"/>
						</xsl:if>
					</DRF_1>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var104_cur" select="."/>
					<DRF_2>
						<xsl:if test="not((translate(s_fecha_inicial_resolucion/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="s_fecha_inicial_resolucion"/>
						</xsl:if>
					</DRF_2>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var105_cur" select="."/>
					<DRF_3>
						<xsl:if test="not((translate(s_fecha_final_resolucion/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="s_fecha_final_resolucion"/>
						</xsl:if>
					</DRF_3>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var106_cur" select="."/>
					<DRF_4>
						<xsl:if test="not((translate(s_prefijo_resolucion/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="s_prefijo_resolucion"/>
						</xsl:if>
					</DRF_4>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var107_cur" select="."/>
					<DRF_5>
						<xsl:if test="not((translate(s_rango_inicial/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="number(s_rango_inicial)"/>
						</xsl:if>
					</DRF_5>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var108_cur" select="."/>
					<DRF_6>
						<xsl:if test="not((translate(s_rango_final/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="number(s_rango_final)"/>
						</xsl:if>
					</DRF_6>
				</xsl:for-each>
			</DRF>
			<xsl:for-each select="dsxml/NOTAS">
				<xsl:variable name="var109_cur" select="."/>
				<NOT>
					<xsl:choose>
						<xsl:when test="(translate(indicador/@xsi:nil, 'true ', '1') = '1')"/>
						<xsl:when test="not((translate(valor/@xsi:nil, 'true ', '1') = '1'))">
							<NOT_1>
								<xsl:value-of select="concat(indicador, valor)"/>
							</NOT_1>
						</xsl:when>
					</xsl:choose>
				</NOT>
			</xsl:for-each>
			<ORC>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var110_cur" select="."/>
					<ORC_1>
						<xsl:if test="not((translate(numero_orden_compra/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="numero_orden_compra"/>
						</xsl:if>
					</ORC_1>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var111_cur" select="."/>
					<ORC_2>
						<xsl:if test="not((translate(fecha_orden_compra/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="fecha_orden_compra"/>
						</xsl:if>
					</ORC_2>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var112_cur" select="."/>
					<ORC_4>
						<xsl:if test="not((translate(numero_pedido/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="numero_pedido"/>
						</xsl:if>
					</ORC_4>
				</xsl:for-each>
			</ORC>
			<xsl:for-each select="dsxml/documentos_referencia">
				<xsl:variable name="var113_cur" select="."/>
				<REF>
					<REF_1>
						<xsl:if test="not((translate(tipo_documento_ref/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="tipo_documento_ref"/>
						</xsl:if>
					</REF_1>
					<REF_2>
						<xsl:if test="not((translate(numero_documento_ref/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="numero_documento_ref"/>
						</xsl:if>
					</REF_2>
					<REF_3>
						<xsl:if test="not((translate(fecha_documento_ref/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="fecha_documento_ref"/>
						</xsl:if>
					</REF_3>
				</REF>
			</xsl:for-each>
			<IEN>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var114_cur" select="."/>
					<IEN_1>
						<xsl:if test="not((translate(direccion_entrega_adquiriente/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="direccion_entrega_adquiriente"/>
						</xsl:if>
					</IEN_1>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var115_cur" select="."/>
					<IEN_4>
						<xsl:if test="not((translate(ciudad_entrega_adquiriente/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="ciudad_entrega_adquiriente"/>
						</xsl:if>
					</IEN_4>
				</xsl:for-each>
				<xsl:for-each select="dsxml/despacho_xml">
					<xsl:variable name="var116_cur" select="."/>
					<IEN_6>
						<xsl:if test="not((translate(codigo_pais_destino/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="codigo_pais_destino"/>
						</xsl:if>
					</IEN_6>
				</xsl:for-each>
				<xsl:for-each select="dsxml/encabezado_xml">
					<xsl:variable name="var117_cur" select="."/>
					<IEN_7>
						<xsl:if test="not((translate(nombre_adquiriente/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="nombre_adquiriente"/>
						</xsl:if>
					</IEN_7>
				</xsl:for-each>
				<IEN_13>
					<xsl:value-of select="'00:00:00'"/>
				</IEN_13>
				<xsl:for-each select="dsxml/despacho_xml">
					<xsl:variable name="var118_cur" select="."/>
					<IEN_17>
						<xsl:if test="not((translate(puerto_embarque/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="puerto_embarque"/>
						</xsl:if>
					</IEN_17>
				</xsl:for-each>
			</IEN>
			<TET>
				<xsl:for-each select="dsxml/terminos_de_negociacion_xml">
					<xsl:variable name="var119_cur" select="."/>
					<TET_2>
						<xsl:if test="not((translate(termino_incoterm/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="termino_incoterm"/>
						</xsl:if>
					</TET_2>
				</xsl:for-each>
				<xsl:for-each select="dsxml/despacho_xml">
					<xsl:variable name="var120_cur" select="."/>
					<TET_4>
						<xsl:if test="not((translate(codigo_pais_origen/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="codigo_pais_origen"/>
						</xsl:if>
					</TET_4>
				</xsl:for-each>
			</TET>
			<xsl:for-each select="dsxml">
				<xsl:variable name="var121_cur" select="."/>
				<xsl:for-each select="pago_xml">
					<xsl:variable name="var122_cur" select="."/>
					<MEP>
						<MEP_1>
							<xsl:if test="not((translate(codigo_medio_pago/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="codigo_medio_pago"/>
							</xsl:if>
						</MEP_1>
						<MEP_2>
							<xsl:if test="not((translate(metodo_pago/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="metodo_pago"/>
							</xsl:if>
						</MEP_2>
						<MEP_3>
							<xsl:if test="not((translate(fecha_vencimiento_pago/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="fecha_vencimiento_pago"/>
							</xsl:if>
						</MEP_3>
						<MEP_4>
							<xsl:if test="not((translate(tipo_pago/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="number(tipo_pago)"/>
							</xsl:if>
						</MEP_4>
						<MEP_5>
							<xsl:if test="not((translate(numero_dias/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="number(numero_dias)"/>
							</xsl:if>
						</MEP_5>
						<xsl:for-each select="$var121_cur/encabezado_xml">
							<xsl:variable name="var123_cur" select="."/>
							<MEP_8>
								<xsl:if test="not((translate(codigo_institucion_financiera/@xsi:nil, 'true ', '1') = '1'))">
									<xsl:value-of select="codigo_institucion_financiera"/>
								</xsl:if>
							</MEP_8>
						</xsl:for-each>
						<xsl:for-each select="$var121_cur/encabezado_xml">
							<xsl:variable name="var124_cur" select="."/>
							<MEP_9>
								<xsl:if test="not((translate(nombre_institucion_financiera/@xsi:nil, 'true ', '1') = '1'))">
									<xsl:value-of select="nombre_institucion_financiera"/>
								</xsl:if>
							</MEP_9>
						</xsl:for-each>
					</MEP>
				</xsl:for-each>
			</xsl:for-each>
			<CNP>
				<xsl:for-each select="dsxml/pago_xml">
					<xsl:variable name="var125_cur" select="."/>
					<CNP_1>
						<xsl:if test="not((translate(condicion_pago/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="number(condicion_pago)"/>
						</xsl:if>
					</CNP_1>
				</xsl:for-each>
				<xsl:for-each select="dsxml/pago_xml">
					<xsl:variable name="var126_cur" select="."/>
					<CNP_2>
						<xsl:if test="not((translate(codigo_tiempo_pago/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="codigo_tiempo_pago"/>
						</xsl:if>
					</CNP_2>
				</xsl:for-each>
			</CNP>
			<CTS>
				<CTS_1>
					<xsl:value-of select="'GRAS03'"/>
				</CTS_1>
			</CTS>
			<xsl:for-each select="dsxml/mandantes_xml">
				<xsl:variable name="var127_cur" select="."/>
				<CDM>
					<CDM_1>
						<xsl:if test="not((translate(numero_contrato/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="numero_contrato"/>
						</xsl:if>
					</CDM_1>
					<CDM_2>
						<xsl:if test="not((translate(tipo_contrato/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="boolean(translate(normalize-space(string(tipo_contrato)), ' 0false', ''))"/>
						</xsl:if>
					</CDM_2>
					<CDM_3>
						<xsl:if test="not((translate(fecha_contrato/@xsi:nil, 'true ', '1') = '1'))">
							<xsl:value-of select="fecha_contrato"/>
						</xsl:if>
					</CDM_3>
				</CDM>
			</xsl:for-each>
			<xsl:for-each select="dsxml">
				<xsl:variable name="var128_cur" select="."/>
				<xsl:for-each select="detalle_xml">
					<xsl:variable name="var129_cur" select="."/>
					<ITE>
						<ITE_1>
							<xsl:if test="not((translate(item/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="number(item)"/>
							</xsl:if>
						</ITE_1>
						<ITE_2>
							<xsl:if test="not((translate(gratis/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="boolean(translate(normalize-space(string(gratis)), ' 0false', ''))"/>
							</xsl:if>
						</ITE_2>
						<ITE_3>
							<xsl:if test="not((translate(cantidad_item/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="number(cantidad_item)"/>
							</xsl:if>
						</ITE_3>
						<ITE_4>
							<xsl:if test="not((translate(unidad_medida/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="unidad_medida"/>
							</xsl:if>
						</ITE_4>
						<ITE_5>
							<xsl:if test="not((translate(precio_bruto/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="number(precio_bruto)"/>
							</xsl:if>
						</ITE_5>
						<xsl:for-each select="$var128_cur/encabezado_xml">
							<xsl:variable name="var130_cur" select="."/>
							<ITE_6>
								<xsl:if test="not((translate(codigo_moneda_emisor/@xsi:nil, 'true ', '1') = '1'))">
									<xsl:value-of select="codigo_moneda_emisor"/>
								</xsl:if>
							</ITE_6>
						</xsl:for-each>
						<ITE_7>
							<xsl:if test="not((translate(precio_unitario_co_rg/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="precio_unitario_co_rg"/>
							</xsl:if>
						</ITE_7>
						<xsl:for-each select="$var128_cur/encabezado_xml">
							<xsl:variable name="var131_cur" select="."/>
							<ITE_8>
								<xsl:if test="not((translate(codigo_moneda_emisor/@xsi:nil, 'true ', '1') = '1'))">
									<xsl:value-of select="codigo_moneda_emisor"/>
								</xsl:if>
							</ITE_8>
						</xsl:for-each>
						<ITE_9>
							<xsl:if test="not((translate(ean_producto/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="ean_producto"/>
							</xsl:if>
						</ITE_9>
						<ITE_10>
							<xsl:if test="not((translate(descripcion_unidad_un/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="descripcion_unidad_un"/>
							</xsl:if>
						</ITE_10>
						<ITE_11>
							<xsl:if test="not((translate(descripcion_item/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="descripcion_item"/>
							</xsl:if>
						</ITE_11>
						<ITE_13>
							<xsl:if test="not((translate(cantidad_unidades/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="floor(cantidad_unidades)"/>
							</xsl:if>
						</ITE_13>
						<ITE_14>
							<xsl:if test="not((translate(unidad_medida/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="unidad_medida"/>
							</xsl:if>
						</ITE_14>
						<ITE_16>
							<xsl:if test="not((translate(cliente_certificado_rspo/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="cliente_certificado_rspo"/>
							</xsl:if>
						</ITE_16>
						<ITE_17>
							<xsl:if test="not((translate(codigo_producto_cliente/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="codigo_producto_cliente"/>
							</xsl:if>
						</ITE_17>
						<ITE_18>
							<xsl:if test="not((translate(codigo_producto_emisor/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="codigo_producto_emisor"/>
							</xsl:if>
						</ITE_18>
						<ITE_19>
							<xsl:if test="not((translate(precio_unitario_bg/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="number(precio_unitario_bg)"/>
							</xsl:if>
						</ITE_19>
						<xsl:for-each select="$var128_cur/encabezado_xml">
							<xsl:variable name="var132_cur" select="."/>
							<ITE_20>
								<xsl:if test="not((translate(codigo_moneda_emisor/@xsi:nil, 'true ', '1') = '1'))">
									<xsl:value-of select="codigo_moneda_emisor"/>
								</xsl:if>
							</ITE_20>
						</xsl:for-each>
						<ITE_21>
							<xsl:if test="not((translate(precio_neto_bg_rg/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="precio_neto_bg_rg"/>
							</xsl:if>
						</ITE_21>
						<xsl:for-each select="$var128_cur/encabezado_xml">
							<xsl:variable name="var133_cur" select="."/>
							<ITE_22>
								<xsl:if test="not((translate(codigo_moneda_emisor/@xsi:nil, 'true ', '1') = '1'))">
									<xsl:value-of select="codigo_moneda_emisor"/>
								</xsl:if>
							</ITE_22>
						</xsl:for-each>
						<ITE_25>
							<xsl:if test="not((translate(numero_contrato/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="numero_contrato"/>
							</xsl:if>
						</ITE_25>
						<ITE_26>
							<xsl:if test="not((translate(nit_mandante/@xsi:nil, 'true ', '1') = '1'))">
								<xsl:value-of select="number(nit_mandante)"/>
							</xsl:if>
						</ITE_26>
						<LOT>
							<LOT_1>
								<xsl:if test="not((translate(lote_producto/@xsi:nil, 'true ', '1') = '1'))">
									<xsl:value-of select="lote_producto"/>
								</xsl:if>
							</LOT_1>
							<LOT_2>
								<xsl:if test="not((translate(fecha_vencimiento_lote/@xsi:nil, 'true ', '1') = '1'))">
									<xsl:value-of select="fecha_vencimiento_lote"/>
								</xsl:if>
							</LOT_2>
						</LOT>
						<xsl:for-each select="documentos_referencia_item">
							<xsl:variable name="var134_cur" select="."/>
							<IRF>
								<IRF_1>
									<xsl:if test="not((translate(tipo_documento_ref/@xsi:nil, 'true ', '1') = '1'))">
										<xsl:value-of select="tipo_documento_ref"/>
									</xsl:if>
								</IRF_1>
								<IRF_2>
									<xsl:if test="not((translate(cliente_numero_recibo/@xsi:nil, 'true ', '1') = '1'))">
										<xsl:value-of select="cliente_numero_recibo"/>
									</xsl:if>
								</IRF_2>
								<IRF_3>
									<xsl:if test="not((translate(cliente_posicion_item_recibo/@xsi:nil, 'true ', '1') = '1'))">
										<xsl:value-of select="cliente_posicion_item_recibo"/>
									</xsl:if>
								</IRF_3>
								<IRF_4>
									<xsl:if test="not((translate(fecha_aviso_recibo/@xsi:nil, 'true ', '1') = '1'))">
										<xsl:value-of select="fecha_aviso_recibo"/>
									</xsl:if>
								</IRF_4>
							</IRF>
						</xsl:for-each>
						<xsl:for-each select="$var128_cur/desgloce_neg_xml">
							<xsl:variable name="var135_cur" select="."/>
							<IDE>
								<IDE_1>
									<xsl:value-of select="boolean(translate(normalize-space('True'), ' 0false', ''))"/>
								</IDE_1>
								<IDE_2>
									<xsl:if test="not((translate(valor_desglose_rg/@xsi:nil, 'true ', '1') = '1'))">
										<xsl:value-of select="number(valor_desglose_rg)"/>
									</xsl:if>
								</IDE_2>
								<xsl:for-each select="$var128_cur/encabezado_xml">
									<xsl:variable name="var136_cur" select="."/>
									<IDE_3>
										<xsl:if test="not((translate(codigo_moneda_emisor/@xsi:nil, 'true ', '1') = '1'))">
											<xsl:value-of select="codigo_moneda_emisor"/>
										</xsl:if>
									</IDE_3>
								</xsl:for-each>
								<IDE_4>
									<xsl:if test="not((translate(cargue/@xsi:nil, 'true ', '1') = '1'))">
										<xsl:value-of select="cargue"/>
									</xsl:if>
								</IDE_4>
								<IDE_9>
									<xsl:if test="not((translate(secuencia/@xsi:nil, 'true ', '1') = '1'))">
										<xsl:value-of select="number(secuencia)"/>
									</xsl:if>
								</IDE_9>
							</IDE>
						</xsl:for-each>
						<TII>
							<xsl:for-each select="item_impto_xml">
								<xsl:variable name="var137_cur" select="."/>
								<TII_1>
									<xsl:if test="not((translate(valor_impuesto/@xsi:nil, 'true ', '1') = '1'))">
										<xsl:value-of select="number(valor_impuesto)"/>
									</xsl:if>
								</TII_1>
							</xsl:for-each>
							<xsl:for-each select="$var128_cur/encabezado_xml">
								<xsl:variable name="var138_cur" select="."/>
								<TII_2>
									<xsl:if test="not((translate(codigo_moneda_emisor/@xsi:nil, 'true ', '1') = '1'))">
										<xsl:value-of select="codigo_moneda_emisor"/>
									</xsl:if>
								</TII_2>
							</xsl:for-each>
							<xsl:for-each select="item_impto_xml">
								<xsl:variable name="var139_cur" select="."/>
								<TII_3>
									<xsl:if test="not((translate(indicador_cargo/@xsi:nil, 'true ', '1') = '1'))">
										<xsl:value-of select="boolean(translate(normalize-space(string(indicador_cargo)), ' 0false', ''))"/>
									</xsl:if>
								</TII_3>
							</xsl:for-each>
							<IIM>
								<xsl:for-each select="item_impto_xml">
									<xsl:variable name="var140_cur" select="."/>
									<IIM_1>
										<xsl:if test="not((translate(codigo_impuesto_dian/@xsi:nil, 'true ', '1') = '1'))">
											<xsl:value-of select="codigo_impuesto_dian"/>
										</xsl:if>
									</IIM_1>
								</xsl:for-each>
								<xsl:for-each select="item_impto_xml">
									<xsl:variable name="var141_cur" select="."/>
									<IIM_2>
										<xsl:if test="not((translate(valor_impuesto/@xsi:nil, 'true ', '1') = '1'))">
											<xsl:value-of select="number(valor_impuesto)"/>
										</xsl:if>
									</IIM_2>
								</xsl:for-each>
								<xsl:for-each select="$var128_cur/encabezado_xml">
									<xsl:variable name="var142_cur" select="."/>
									<IIM_3>
										<xsl:if test="not((translate(codigo_moneda_emisor/@xsi:nil, 'true ', '1') = '1'))">
											<xsl:value-of select="codigo_moneda_emisor"/>
										</xsl:if>
									</IIM_3>
								</xsl:for-each>
								<xsl:for-each select="item_impto_xml">
									<xsl:variable name="var143_cur" select="."/>
									<IIM_4>
										<xsl:if test="not((translate(base_imponible/@xsi:nil, 'true ', '1') = '1'))">
											<xsl:value-of select="number(base_imponible)"/>
										</xsl:if>
									</IIM_4>
								</xsl:for-each>
								<xsl:for-each select="$var128_cur/encabezado_xml">
									<xsl:variable name="var144_cur" select="."/>
									<IIM_5>
										<xsl:if test="not((translate(codigo_moneda_emisor/@xsi:nil, 'true ', '1') = '1'))">
											<xsl:value-of select="codigo_moneda_emisor"/>
										</xsl:if>
									</IIM_5>
								</xsl:for-each>
								<xsl:for-each select="item_impto_xml">
									<xsl:variable name="var145_cur" select="."/>
									<IIM_6>
										<xsl:if test="not((translate(porcentaje/@xsi:nil, 'true ', '1') = '1'))">
											<xsl:value-of select="number(porcentaje)"/>
										</xsl:if>
									</IIM_6>
								</xsl:for-each>
							</IIM>
						</TII>
					</ITE>
				</xsl:for-each>
			</xsl:for-each>
		</FACTURA>
	</xsl:template>
</xsl:stylesheet>
